### ISSUE TITLE
Time displayed seems skewed, possibly by timezone issues

### ISSUE THREAD

**Issue by MarkBaker** [TomasVotruba/friendsofphp.org#192]
Looking at the list for the coming weeks from here in the Netherlands (CET, UTC+1), I see two meetings on Tue, Feb 15, both showing the time as 19:00
 - Athens Laravel (Greece timezone, EET, UTC+2)
 - PHP Cambridge (UK timezone, GMT, UTC+0)

![image](https://user-images.githubusercontent.com/770298/152975470-4475784a-3a07-4824-8c8c-24db999b7a39.png)

If I visit the meetup pages for each
 - Athens Laravel shows "Tuesday, February 15, 2022 6:00 PM to 7:00 PM CET"
 - PHP Cambridge shows "Tuesday, February 15, 2022 8:00 PM to 10:00 PM CET"

![image](https://user-images.githubusercontent.com/770298/152975788-9fd0cea1-4174-47c0-9a6a-d7ea82d7c775.png)

![image](https://user-images.githubusercontent.com/770298/152975700-576f7e9a-f676-4789-8d22-cf3bd038c515.png)

Both CET times according to the meetup pages; which is correct for my timezone; but doesn't match with the start times on the friendsofphp.org page, which looks as though it has read the meetup times as local EET and GMT timezones respectively, and converted them to CET.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

This might be also part of UX improvement.
What would you expect to find on the website?

**Comment by MarkBaker** [comment]
I'd expect to see either
 - A confirmation that I was seeing times in my own timezone (CET), with the correct CET start times displayed for each meetup

```
All times are shown in your local timezone (CET)

When             | Where
-----------------|---------------------------
Tue Feb 15 18:00 | Athens, Greece
Tue Feb 15 20:00 | Cambridge, United Kingdom
```

or
 - The start times for the meetup with the timezone for that meetup

```
When                 | Where
---------------------|---------------------------
Tue Feb 15 19:00 EET | Athens, Greece
Tue Feb 15 19:00 GMT | Cambridge, United Kingdom
```

The first option would probably be a better UX, and matches the times that I see when I go to the meetup page, already adjusted to my timezone. I'm seeing the times as they relate to my current timezone, so I don't have to do any mental adjustments to account for a timezone difference.

It's probably the more complicated approach technically, especially as it has to take into account the switch to daylight savings in each location (particularly impirtant when viewing US times from Europe, or vice versa), and could even affect the date, and not simply the time (an evening meetup in Hawaii could become the early hours of the following morning for somebody in Asia).

But what's most important, whichever approach is used, is to display he correct starting time.

**Comment by TomasVotruba** [comment]
The website is fully static, so the current time zone is not possible.

The 2nd option, meetup.com original time zone info, seems doable 👍

**Comment by TomasVotruba** [comment]
I'm just checking the data, because I got confused in a long issue text :)

The data are actually correct, it's always the meetup local time. So 19:00 meetup in Athens means 19:00 for people form Athens. 
Same goes for Cambridge.

We could add some external link for converting local time to UTC thoguh.

**Comment by TomasVotruba** [comment]
See https://github.com/TomasVotruba/friendsofphp.org/pull/194

**Comment by MarkBaker** [comment]
At a minimum, it wold probably be good to indicate that the times displayed are local times for the timezone of the meetup

**Comment by TomasVotruba** [comment]
Google might help ↓

["19:00 Athens in my time"](https://www.google.com/search?q=19%3A00+athens+in+my+time&sxsrf=APq-WBvYoSbqJXAts_YsrUE8PMtsWg2mPw%3A1644420079668&source=hp&ei=79sDYrjeJbqFxc8Pj4SF-AI&iflsig=AHkkrS4AAAAAYgPp_93yj9DmLeIR9_m3IxQwpWtqMa5-&ved=0ahUKEwj4kdSV9vL1AhW6QvEDHQ9CAS8Q4dUDCAc&uact=5&oq=19%3A00+athens+in+my+time&gs_lcp=Cgdnd3Mtd2l6EAM6BAgjECc6BQgAEJECOgUIABCABDoFCC4QgARQAFj7GmCJHGgAcAB4AIABowGIAbgTkgEENS4xN5gBAKABAQ&sclient=gws-wiz)

**Comment by MarkBaker** [comment]
And that way, you don't need to specify the local timezone, but still make it clear that it is a local time
