### ISSUE TITLE
Crawl and use structured data

### ISSUE THREAD

**Issue by qdequippe** [TomasVotruba/friendsofphp.org#201]
Hi,

Are you open to a pull request transforming events import using crawling + structured data?

On each events page there is [Event](https://schema.org/Event) structured data (see https://validator.schema.org/#url=https%3A%2F%2Fwww.meetup.com%2Fsfugcgn%2Fevents%2F for example).

**Comment by TomasVotruba** [comment]
> Hi,
>
> Are you open to a pull request transforming events import using crawling + structured data?

Hi, thanks for reaching out! 

If you find a way to keep this active, go for it :muscle:
